name: ddd_arch
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # state management
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  rxdart: ^0.27.7
  provider: ^6.0.5

  # models, entities related
  equatable: ^2.0.5
  tuple: ^2.0.1

  # build_runner
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  injectable: 

  # storage
  shared_preferences: ^2.0.17
  flutter_secure_storage: ^8.0.0

  # data format
  intl: ^0.17.0
  dartx: ^1.1.0

  # http
  dio: ^5.0.0

  # connectivity
  connectivity_plus: ^3.0.3
  internet_connection_checker: ^1.0.0+1

  # others
  package_info_plus: ^3.0.3
  reactive_forms: ^14.1.0
  flutter_screenutil: ^5.6.1
  device_preview: ^1.1.0
  google_fonts: ^4.0.3
  objectbox: ^1.7.2
  objectbox_flutter_libs: any

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
  injectable_generator: 
  auto_route_generator: ^5.0.3
  build_runner: 
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  objectbox_generator: any
  
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
