name: ddd_arch
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.1

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  intl: ^0.17.0
  injectable: 
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.17
  rxdart: ^0.27.7
  equatable: ^2.0.5

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
  injectable_generator: 
  build_runner: 
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  generate: true
